language: c

#######################################################################################


os:
  - linux


#######################################################################################


before_install:

  - sudo apt-get update -qq
  
  # downloading the latest version of the linaro toolchain. 
  - git clone https://andrea2107@bitbucket.org/UBERTC/aarch64-linux-android-4.9-kernel.git
  - export PATH=$PATH:$PWD/aarch64-linux-android-4.9-kernel/bin/
  - sudo apt-get install bc


#######################################################################################





script:

  # exporting the variable to be used by make utility  
  - export TOP=$(pwd)
  - export ARCH=arm64
  - export CONFIG_NO_ERROR_ON_MISMATCH=y
  - export CROSS_COMPILE=aarch64-linux-android- 

  # download the .config file for the chosen linux version and
  # preparing the kernel source
  
  - mkdir -p $TOP/KERNEL_OBJ
  - make O=$TOP/KERNEL_OBJ ARCH=arm64 MTK_TARGET_PROJECT=hermes TARGET_BUILD_VARIANT=user CROSS_COMPILE=$TOOLCHAIN ROOTDIR=$TOP hermes_defconfig
  - make mrproper && make clobber
  - make O=$TOP/KERNEL_OBJ ROOTDIR=$TOP
