language: c

#######################################################################################


os:
  - linux


#######################################################################################


before_install:

  - sudo apt-get update -qq
   
  - git clone https://andrea2107@bitbucket.org/UBERTC/aarch64-linux-android-4.9-kernel.git
  - sudo apt-get install bc







script:

 
  - export TOP=$(pwd)
  - export ARCH=arm64
  - export CONFIG_NO_ERROR_ON_MISMATCH=y
  - export CROSS_COMPILE=aarch64-linux-android-4.9-kernel/bin/aarch64-linux-android- 

  - mkdir -p $TOP/KERNEL_OBJ
  - make O=$TOP/KERNEL_OBJ ARCH=arm64 MTK_TARGET_PROJECT=hermes TARGET_BUILD_VARIANT=user CROSS_COMPILE=$TOOLCHAIN ROOTDIR=$TOP hermes_defconfig
  - make mrproper
  - make O=$TOP/KERNEL_OBJ ROOTDIR=$TOP
